### ISSUE TITLE
More drag events

### ISSUE THREAD

**Issue by pofulu** [Bunny83/UnityWindowsFileDrag-Drop#8]
Is it possible to get the DragEnter, DragExit and DragMove event?
For example, drag file to specific area in Unity window, and the uGUI can response when the dragging mouse over it.
I tested to edit the WM_XX, but when I start dragging file, the event just become to TIMER.

**Comment by Bunny83** [comment]
Windows does not provide such generic windows messages for dragging files. There is only the WM_DROPFILES message that is send to your window. To get a more sophisticated drag and drop behaviour you have to register an actual IDropHandler and register it with [RegisterDragDrop](https://docs.microsoft.com/en-us/windows/win32/api/ole2/nf-ole2-registerdragdrop). However dealing with OLE stuff from managed code is a pain. Also not having direct access to the window doesn't really help the situation. Though technically everything is possible one way or the other. This solution here just reacts to the WM_DROPFILES message, nothing more -.-
